# ===============================
# 1. Load required libraries
# ===============================
library(DESeq2)
library(pheatmap)
library(ggplot2)

# ===============================
# 2. Import count data and metadata
# ===============================
# Read counts file (generated by featureCounts)
fc <- read.delim("gene_counts.txt", comment.char = "#", check.names = FALSE)
head(fc)

# Load counts and metadata
c_e_count <- read.delim('gene_counts.txt', header = T)
c_e_meta <- read.delim('metadata.tsv', header = T, stringsAsFactors = T)

# Quick preview of input data
head(c_e_count)
head(c_e_meta)

# ===============================
# 3. Prepare count matrix
# ===============================
# Keep only relevant columns: Gene IDs + sample counts
raw_counts <- fc[, c("Geneid", grep("^SRR", colnames(fc), value = TRUE))]
head(raw_counts)

# Set gene IDs as rownames
rownames(raw_counts) <- c_e_count$Geneid
raw_counts <- raw_counts[ , -1]  # remove Geneid column
head(raw_counts)

# ===============================
# 4. Create DESeq2 dataset object
# ===============================
dds <- DESeqDataSetFromMatrix(countData = raw_counts,
                              colData = c_e_meta,
                              design = ~State)

# Preview metadata inside DESeq2 object
dds
dds$SRA.Accession.Number
dds$Age
dds$State

# Set Healthy_control as reference group
dds$State <- relevel(dds$State, ref = "Healthy_control")

# Full design: include Age as covariate + State
design(dds) <- ~ Age + State

# ===============================
# 5. Run DESeq2 pipeline
# ===============================
dds <- DESeq(dds)

# ===============================
# 6. PCA analysis (sample clustering)
# ===============================
vsd <- vst(dds, blind = TRUE)
pcaData <- plotPCA(vsd, intgroup = c("State", "Age"), returnData = TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))

ggplot(pcaData, aes(PC1, PC2, color = State, shape = State, size = Age)) +
  geom_point(alpha = 0.8) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
  ggtitle("PCA of RNA-seq samples") +
  scale_size_continuous(range = c(3,6)) +
  theme_minimal()

# ===============================
# 7. Differential expression analysis
# ===============================
# Using FDR threshold = 0.05
final_res <- results(dds, contrast = c("State", "Bipolar_disorder", "Healthy_control"), alpha = 0.05)

# Inspect results
head(final_res)
summary(final_res)
sum(final_res$padj < 0.05, na.rm = TRUE)

# ===============================
# 8. Distribution of p-values
# ===============================
plot(density(x = na.omit(final_res$pvalue)))

# ===============================
# 9. Volcano plot
# ===============================
plot(x = final_res$log2FoldChange, 
     y = -log10(final_res$pvalue), 
     cex = 0.25,
     pch = 19, 
     col = 'grey',
     ylab = '-log10(p-value)',
     xlab = 'Log2 Fold Change')

# Add thresholds (log2FC ±1, FDR < 0.05)
abline(v = c(-1, 1), lty = 2)  
abline(h = -log10(0.05), lty = 2)  

# Highlight significant genes
upregulated <- subset(final_res, padj < 0.05 & log2FoldChange > 1)
downregulated <- subset(final_res, padj < 0.05 & log2FoldChange < -1)

points(upregulated$log2FoldChange,
       -log10(upregulated$pvalue),
       cex = 0.5, col = 'red', pch = 19)

points(downregulated$log2FoldChange,
       -log10(downregulated$pvalue),
       cex = 0.5, col = 'blue', pch = 19)

mtext('Volcano plot (FDR < 0.05, |LFC| > 1)')

# ===============================
# 10. Heatmap of DEGs
# ===============================
# Use only significantly differentially expressed genes
vsd <- vst(dds, blind = FALSE)
mat <- assay(vsd)

sel <- with(as.data.frame(final_res),
            which(!is.na(padj) & padj < 0.05 & abs(log2FoldChange) > 1))

# If too few DEGs, take top 300 most variable genes
if (length(sel) < 30) {
  v <- rowVars(mat)
  sel <- head(order(v, decreasing = TRUE), 300)
}

mat_sub <- mat[sel, ]

# Standardize (z-score per gene)
mat_sub <- t(scale(t(mat_sub)))

# Sample annotations
ann_col <- as.data.frame(colData(dds)[, c("State","Age")])
ann_colors <- list(
  State = c(Bipolar_disorder = "tomato", Healthy_control = "steelblue")
)

# Draw heatmap
pheatmap(mat_sub,
         cluster_rows = TRUE,
         cluster_cols = TRUE,
         show_rownames = FALSE,
         annotation_col = ann_col,
         annotation_colors = ann_colors,
         fontsize_col = 10,
         scale = "none")

# ===============================
# 11. Export gene list for enrichment (ShinyGO)
# ===============================
gene_list <- rownames(subset(final_res, padj < 0.1 & abs(log2FoldChange) > 1))
write.csv(gene_list, 'gene_list.csv')

# Next step: upload gene_list.csv to ShinyGO or another enrichment tool
